name: Github Actions Linter
on:
  workflow_dispatch:

jobs:
  Action-lint:
    if: github.event_name != 'opened'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Linter
        run: brew install actionlint
      - name: Execute Linter
        run: actionlint
