name: Github Container Registry
on:
  pull_request: 
    branches: [develop, staging, master]
    types: [opened, synchronize]
  release:
    types: [published]

jobs:
  PR-Title:
    uses: ./.github/workflows/pr-title.yml

  Docker-Linter:
    uses: ./.github/workflows/docker-linter.yml
    needs: [PR-Title]