name: Github Container Registry
on:
  pull_request: 
    branches: [develop, staging, master]
    types: [opened, synchronize]
  release:
    types: [published]

jobs:
  PR-Title:
    uses: ./.github/workflows/pr-title.yml
    secrets:
      PAT_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}

  Docker-Linter:
    uses: ./.github/workflows/docker-linter.yml
    needs: [PR-Title]

  Security-Anchore:
    uses: ./.github/workflows/anchore.yml
    needs: [PR-Title, Docker-Linter]
  
  Security-Snyk:
    uses: ./.github/workflows/snyk.yml
    needs: [PR-Title, Docker-Linter]
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}